name: Build and Release App

on:
  push: 
    branches: [main]
jobs:
  build-project:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build Site
        run: npm run build
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: next-ci-cd
          heroku_email: abenezerzeleke9@gmail.com
