name: Build and Release App

on:
  push: 
    branches: [main]
jobs:
  build-project:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: Install NPM dependencies
        run: npm install
      - name: Build Site
        run: npm run build
