name: Build and Release App

on:
  push: 
    branches: [main]
jobs:
  build-project:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        uses: npm Install
      - name: Build Site
        uses: npm run build
